<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-06-03T08:14:52 IST" name="Suite" finished-at="2023-06-03T08:15:24 IST" duration-ms="31929">
    <groups>
      <group name="Master">
        <method signature="TC_001_AcctRegistration.test_account_registration()[pri:0, instance:testCases.TC_001_AcctRegistration@79e2c065]" name="test_account_registration" class="testCases.TC_001_AcctRegistration"/>
      </group> <!-- Master -->
      <group name="Regression">
        <method signature="TC_001_AcctRegistration.test_account_registration()[pri:0, instance:testCases.TC_001_AcctRegistration@79e2c065]" name="test_account_registration" class="testCases.TC_001_AcctRegistration"/>
      </group> <!-- Regression -->
    </groups>
    <test started-at="2023-06-03T08:14:52 IST" name="Test" finished-at="2023-06-03T08:15:24 IST" duration-ms="31929">
      <class name="testCases.TC_001_AcctRegistration">
        <test-method is-config="true" signature="setUp(java.lang.String)[pri:0, instance:testCases.TC_001_AcctRegistration@79e2c065]" started-at="2023-06-03T08:14:52 IST" name="setUp" finished-at="2023-06-03T08:15:16 IST" duration-ms="23977" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="test_account_registration()[pri:0, instance:testCases.TC_001_AcctRegistration@79e2c065]" started-at="2023-06-03T08:15:16 IST" name="test_account_registration" finished-at="2023-06-03T08:15:22 IST" duration-ms="5660" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[confirmation message differs expected [Your account has been created!] but found [Register Account]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: confirmation message differs expected [Your account has been created!] but found [Register Account]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at testCases.TC_001_AcctRegistration.test_account_registration(TC_001_AcctRegistration.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test_account_registration -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:testCases.TC_001_AcctRegistration@79e2c065]" started-at="2023-06-03T08:15:24 IST" name="tearDown" finished-at="2023-06-03T08:15:24 IST" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testCases.TC_001_AcctRegistration -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
